import math

WHEEL_RADIUS_M = 0.035
ENCODER_TICKS_PER_REV = 990
ENCODER_TICKS_PER_M = ENCODER_TICKS_PER_REV / (math.tau * WHEEL_RADIUS_M)
FULL_SPEED_TICKS_PER_S = 1750.0
FULL_SPEED_RIM_M_S = FULL_SPEED_TICKS_PER_S / ENCODER_TICKS_PER_M
WHEEL_BASE_RADIUS_M = 0.1
FULL_SPEED_YAW_RATE_RAD_S = FULL_SPEED_RIM_M_S / WHEEL_BASE_RADIUS_M
COMMAND_WATCHDOG_S = 0.2

ROBOT_RADIUS_M = 0.17
LIDAR_SELF_RETURN_RANGE_M = ROBOT_RADIUS_M + 0.01

BATTERY_FULL_V = 16.8
BATTERY_EMPTY_V = 13.0
BATTERY_CRITICAL_V = 12.8

HOKUYO_STEPS_PER_REV = 1024
HOKUYO_FRONT_STEP = 384
HOKUYO_FIRST_STEP = 44
HOKUYO_LAST_STEP = 725
HOKUYO_MIN_RANGE_M = 0.02
HOKUYO_MAX_RANGE_M = 5.6
HOKUYO_STEP_ANGLES_RAD = tuple(
    (step - HOKUYO_FRONT_STEP) * math.tau / HOKUYO_STEPS_PER_REV
    for step in range(HOKUYO_FIRST_STEP, HOKUYO_LAST_STEP + 1)
)
